// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: v1/network_node.proto

package network_nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MLNodeTrainStatusEnum int32

const (
	MLNodeTrainStatusEnum_OK         MLNodeTrainStatusEnum = 0
	MLNodeTrainStatusEnum_ERROR      MLNodeTrainStatusEnum = 1
	MLNodeTrainStatusEnum_JOINED     MLNodeTrainStatusEnum = 2
	MLNodeTrainStatusEnum_NOT_JOINED MLNodeTrainStatusEnum = 3
)

// Enum value maps for MLNodeTrainStatusEnum.
var (
	MLNodeTrainStatusEnum_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "JOINED",
		3: "NOT_JOINED",
	}
	MLNodeTrainStatusEnum_value = map[string]int32{
		"OK":         0,
		"ERROR":      1,
		"JOINED":     2,
		"NOT_JOINED": 3,
	}
)

func (x MLNodeTrainStatusEnum) Enum() *MLNodeTrainStatusEnum {
	p := new(MLNodeTrainStatusEnum)
	*p = x
	return p
}

func (x MLNodeTrainStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MLNodeTrainStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_network_node_proto_enumTypes[0].Descriptor()
}

func (MLNodeTrainStatusEnum) Type() protoreflect.EnumType {
	return &file_v1_network_node_proto_enumTypes[0]
}

func (x MLNodeTrainStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MLNodeTrainStatusEnum.Descriptor instead.
func (MLNodeTrainStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{0}
}

type HeartbeatStatusEnum int32

const (
	HeartbeatStatusEnum_HEARTBEAT_OK    HeartbeatStatusEnum = 0
	HeartbeatStatusEnum_HEARTBEAT_ERROR HeartbeatStatusEnum = 1
)

// Enum value maps for HeartbeatStatusEnum.
var (
	HeartbeatStatusEnum_name = map[int32]string{
		0: "HEARTBEAT_OK",
		1: "HEARTBEAT_ERROR",
	}
	HeartbeatStatusEnum_value = map[string]int32{
		"HEARTBEAT_OK":    0,
		"HEARTBEAT_ERROR": 1,
	}
)

func (x HeartbeatStatusEnum) Enum() *HeartbeatStatusEnum {
	p := new(HeartbeatStatusEnum)
	*p = x
	return p
}

func (x HeartbeatStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_network_node_proto_enumTypes[1].Descriptor()
}

func (HeartbeatStatusEnum) Type() protoreflect.EnumType {
	return &file_v1_network_node_proto_enumTypes[1]
}

func (x HeartbeatStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatStatusEnum.Descriptor instead.
func (HeartbeatStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{1}
}

type BarrierStatusEnum int32

const (
	BarrierStatusEnum_READY     BarrierStatusEnum = 0
	BarrierStatusEnum_NOT_READY BarrierStatusEnum = 1
)

// Enum value maps for BarrierStatusEnum.
var (
	BarrierStatusEnum_name = map[int32]string{
		0: "READY",
		1: "NOT_READY",
	}
	BarrierStatusEnum_value = map[string]int32{
		"READY":     0,
		"NOT_READY": 1,
	}
)

func (x BarrierStatusEnum) Enum() *BarrierStatusEnum {
	p := new(BarrierStatusEnum)
	*p = x
	return p
}

func (x BarrierStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BarrierStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_network_node_proto_enumTypes[2].Descriptor()
}

func (BarrierStatusEnum) Type() protoreflect.EnumType {
	return &file_v1_network_node_proto_enumTypes[2]
}

func (x BarrierStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BarrierStatusEnum.Descriptor instead.
func (BarrierStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{2}
}

type StoreRecordStatusEnum int32

const (
	StoreRecordStatusEnum_SET_RECORD_OK    StoreRecordStatusEnum = 0
	StoreRecordStatusEnum_SET_RECORD_ERROR StoreRecordStatusEnum = 1
)

// Enum value maps for StoreRecordStatusEnum.
var (
	StoreRecordStatusEnum_name = map[int32]string{
		0: "SET_RECORD_OK",
		1: "SET_RECORD_ERROR",
	}
	StoreRecordStatusEnum_value = map[string]int32{
		"SET_RECORD_OK":    0,
		"SET_RECORD_ERROR": 1,
	}
)

func (x StoreRecordStatusEnum) Enum() *StoreRecordStatusEnum {
	p := new(StoreRecordStatusEnum)
	*p = x
	return p
}

func (x StoreRecordStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreRecordStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_network_node_proto_enumTypes[3].Descriptor()
}

func (StoreRecordStatusEnum) Type() protoreflect.EnumType {
	return &file_v1_network_node_proto_enumTypes[3]
}

func (x StoreRecordStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreRecordStatusEnum.Descriptor instead.
func (StoreRecordStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{3}
}

type JoinTrainingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RunId         uint64                 `protobuf:"varint,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OuterStep     int32                  `protobuf:"varint,3,opt,name=outer_step,json=outerStep,proto3" json:"outer_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTrainingRequest) Reset() {
	*x = JoinTrainingRequest{}
	mi := &file_v1_network_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTrainingRequest) ProtoMessage() {}

func (x *JoinTrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTrainingRequest.ProtoReflect.Descriptor instead.
func (*JoinTrainingRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{0}
}

func (x *JoinTrainingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinTrainingRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *JoinTrainingRequest) GetOuterStep() int32 {
	if x != nil {
		return x.OuterStep
	}
	return 0
}

type MLNodeTrainStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MLNodeTrainStatusEnum  `protobuf:"varint,1,opt,name=status,proto3,enum=network_node.v1.MLNodeTrainStatusEnum" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OuterStep     int32                  `protobuf:"varint,3,opt,name=outer_step,json=outerStep,proto3" json:"outer_step,omitempty"`
	ActiveNodes   []string               `protobuf:"bytes,4,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLNodeTrainStatus) Reset() {
	*x = MLNodeTrainStatus{}
	mi := &file_v1_network_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLNodeTrainStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLNodeTrainStatus) ProtoMessage() {}

func (x *MLNodeTrainStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLNodeTrainStatus.ProtoReflect.Descriptor instead.
func (*MLNodeTrainStatus) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{1}
}

func (x *MLNodeTrainStatus) GetStatus() MLNodeTrainStatusEnum {
	if x != nil {
		return x.Status
	}
	return MLNodeTrainStatusEnum_OK
}

func (x *MLNodeTrainStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MLNodeTrainStatus) GetOuterStep() int32 {
	if x != nil {
		return x.OuterStep
	}
	return 0
}

func (x *MLNodeTrainStatus) GetActiveNodes() []string {
	if x != nil {
		return x.ActiveNodes
	}
	return nil
}

func (x *MLNodeTrainStatus) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RunId         uint64                 `protobuf:"varint,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	LocalRank     int32                  `protobuf:"varint,3,opt,name=local_rank,json=localRank,proto3" json:"local_rank,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InnerStep     int32                  `protobuf:"varint,5,opt,name=inner_step,json=innerStep,proto3" json:"inner_step,omitempty"`
	OuterStep     int32                  `protobuf:"varint,6,opt,name=outer_step,json=outerStep,proto3" json:"outer_step,omitempty"`
	Epoch         int32                  `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_v1_network_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *HeartbeatRequest) GetLocalRank() int32 {
	if x != nil {
		return x.LocalRank
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetInnerStep() int32 {
	if x != nil {
		return x.InnerStep
	}
	return 0
}

func (x *HeartbeatRequest) GetOuterStep() int32 {
	if x != nil {
		return x.OuterStep
	}
	return 0
}

func (x *HeartbeatRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HeartbeatStatusEnum    `protobuf:"varint,1,opt,name=status,proto3,enum=network_node.v1.HeartbeatStatusEnum" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_v1_network_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() HeartbeatStatusEnum {
	if x != nil {
		return x.Status
	}
	return HeartbeatStatusEnum_HEARTBEAT_OK
}

type GetAliveNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         uint64                 `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OuterStep     int32                  `protobuf:"varint,2,opt,name=outer_step,json=outerStep,proto3" json:"outer_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliveNodesRequest) Reset() {
	*x = GetAliveNodesRequest{}
	mi := &file_v1_network_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliveNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliveNodesRequest) ProtoMessage() {}

func (x *GetAliveNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliveNodesRequest.ProtoReflect.Descriptor instead.
func (*GetAliveNodesRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetAliveNodesRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *GetAliveNodesRequest) GetOuterStep() int32 {
	if x != nil {
		return x.OuterStep
	}
	return 0
}

type GetAliveNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AliveNodes    []string               `protobuf:"bytes,1,rep,name=alive_nodes,json=aliveNodes,proto3" json:"alive_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliveNodesResponse) Reset() {
	*x = GetAliveNodesResponse{}
	mi := &file_v1_network_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliveNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliveNodesResponse) ProtoMessage() {}

func (x *GetAliveNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliveNodesResponse.ProtoReflect.Descriptor instead.
func (*GetAliveNodesResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetAliveNodesResponse) GetAliveNodes() []string {
	if x != nil {
		return x.AliveNodes
	}
	return nil
}

type SetBarrierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarrierId     string                 `protobuf:"bytes,1,opt,name=barrier_id,json=barrierId,proto3" json:"barrier_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RunId         uint64                 `protobuf:"varint,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OuterStep     int32                  `protobuf:"varint,4,opt,name=outer_step,json=outerStep,proto3" json:"outer_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBarrierRequest) Reset() {
	*x = SetBarrierRequest{}
	mi := &file_v1_network_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBarrierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBarrierRequest) ProtoMessage() {}

func (x *SetBarrierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBarrierRequest.ProtoReflect.Descriptor instead.
func (*SetBarrierRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{6}
}

func (x *SetBarrierRequest) GetBarrierId() string {
	if x != nil {
		return x.BarrierId
	}
	return ""
}

func (x *SetBarrierRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetBarrierRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *SetBarrierRequest) GetOuterStep() int32 {
	if x != nil {
		return x.OuterStep
	}
	return 0
}

type SetBarrierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        BarrierStatusEnum      `protobuf:"varint,1,opt,name=status,proto3,enum=network_node.v1.BarrierStatusEnum" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBarrierResponse) Reset() {
	*x = SetBarrierResponse{}
	mi := &file_v1_network_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBarrierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBarrierResponse) ProtoMessage() {}

func (x *SetBarrierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBarrierResponse.ProtoReflect.Descriptor instead.
func (*SetBarrierResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{7}
}

func (x *SetBarrierResponse) GetStatus() BarrierStatusEnum {
	if x != nil {
		return x.Status
	}
	return BarrierStatusEnum_READY
}

type GetBarrierStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarrierId     string                 `protobuf:"bytes,1,opt,name=barrier_id,json=barrierId,proto3" json:"barrier_id,omitempty"`
	RunId         uint64                 `protobuf:"varint,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OuterStep     int32                  `protobuf:"varint,3,opt,name=outer_step,json=outerStep,proto3" json:"outer_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarrierStatusRequest) Reset() {
	*x = GetBarrierStatusRequest{}
	mi := &file_v1_network_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarrierStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarrierStatusRequest) ProtoMessage() {}

func (x *GetBarrierStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarrierStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBarrierStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{8}
}

func (x *GetBarrierStatusRequest) GetBarrierId() string {
	if x != nil {
		return x.BarrierId
	}
	return ""
}

func (x *GetBarrierStatusRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *GetBarrierStatusRequest) GetOuterStep() int32 {
	if x != nil {
		return x.OuterStep
	}
	return 0
}

type GetBarrierStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllReady      bool                   `protobuf:"varint,1,opt,name=all_ready,json=allReady,proto3" json:"all_ready,omitempty"`
	NotReady      []string               `protobuf:"bytes,2,rep,name=not_ready,json=notReady,proto3" json:"not_ready,omitempty"`
	AliveNodes    []string               `protobuf:"bytes,3,rep,name=alive_nodes,json=aliveNodes,proto3" json:"alive_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarrierStatusResponse) Reset() {
	*x = GetBarrierStatusResponse{}
	mi := &file_v1_network_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarrierStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarrierStatusResponse) ProtoMessage() {}

func (x *GetBarrierStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarrierStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBarrierStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{9}
}

func (x *GetBarrierStatusResponse) GetAllReady() bool {
	if x != nil {
		return x.AllReady
	}
	return false
}

func (x *GetBarrierStatusResponse) GetNotReady() []string {
	if x != nil {
		return x.NotReady
	}
	return nil
}

func (x *GetBarrierStatusResponse) GetAliveNodes() []string {
	if x != nil {
		return x.AliveNodes
	}
	return nil
}

type SetStoreRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         uint64                 `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStoreRecordRequest) Reset() {
	*x = SetStoreRecordRequest{}
	mi := &file_v1_network_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStoreRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStoreRecordRequest) ProtoMessage() {}

func (x *SetStoreRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStoreRecordRequest.ProtoReflect.Descriptor instead.
func (*SetStoreRecordRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{10}
}

func (x *SetStoreRecordRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *SetStoreRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_v1_network_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{11}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetStoreRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StoreRecordStatusEnum  `protobuf:"varint,1,opt,name=status,proto3,enum=network_node.v1.StoreRecordStatusEnum" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStoreRecordResponse) Reset() {
	*x = SetStoreRecordResponse{}
	mi := &file_v1_network_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStoreRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStoreRecordResponse) ProtoMessage() {}

func (x *SetStoreRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStoreRecordResponse.ProtoReflect.Descriptor instead.
func (*SetStoreRecordResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{12}
}

func (x *SetStoreRecordResponse) GetStatus() StoreRecordStatusEnum {
	if x != nil {
		return x.Status
	}
	return StoreRecordStatusEnum_SET_RECORD_OK
}

type GetStoreRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         uint64                 `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRecordRequest) Reset() {
	*x = GetStoreRecordRequest{}
	mi := &file_v1_network_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRecordRequest) ProtoMessage() {}

func (x *GetStoreRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRecordRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRecordRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{13}
}

func (x *GetStoreRecordRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *GetStoreRecordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStoreRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRecordResponse) Reset() {
	*x = GetStoreRecordResponse{}
	mi := &file_v1_network_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRecordResponse) ProtoMessage() {}

func (x *GetStoreRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRecordResponse.ProtoReflect.Descriptor instead.
func (*GetStoreRecordResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{14}
}

func (x *GetStoreRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type StoreListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         uint64                 `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListKeysRequest) Reset() {
	*x = StoreListKeysRequest{}
	mi := &file_v1_network_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListKeysRequest) ProtoMessage() {}

func (x *StoreListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListKeysRequest.ProtoReflect.Descriptor instead.
func (*StoreListKeysRequest) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{15}
}

func (x *StoreListKeysRequest) GetRunId() uint64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

type StoreListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreListKeysResponse) Reset() {
	*x = StoreListKeysResponse{}
	mi := &file_v1_network_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListKeysResponse) ProtoMessage() {}

func (x *StoreListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_network_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreListKeysResponse.ProtoReflect.Descriptor instead.
func (*StoreListKeysResponse) Descriptor() ([]byte, []int) {
	return file_v1_network_node_proto_rawDescGZIP(), []int{16}
}

func (x *StoreListKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_v1_network_node_proto protoreflect.FileDescriptor

const file_v1_network_node_proto_rawDesc = "" +
	"\n" +
	"\x15v1/network_node.proto\x12\x0fnetwork_node.v1\"d\n" +
	"\x13JoinTrainingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\x04R\x05runId\x12\x1d\n" +
	"\n" +
	"outer_step\x18\x03 \x01(\x05R\touterStep\"\xc2\x01\n" +
	"\x11MLNodeTrainStatus\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.network_node.v1.MLNodeTrainStatusEnumR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"outer_step\x18\x03 \x01(\x05R\touterStep\x12!\n" +
	"\factive_nodes\x18\x04 \x03(\tR\vactiveNodes\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\"\xd3\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\x04R\x05runId\x12\x1d\n" +
	"\n" +
	"local_rank\x18\x03 \x01(\x05R\tlocalRank\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x01R\ttimestamp\x12\x1d\n" +
	"\n" +
	"inner_step\x18\x05 \x01(\x05R\tinnerStep\x12\x1d\n" +
	"\n" +
	"outer_step\x18\x06 \x01(\x05R\touterStep\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x05R\x05epoch\"Q\n" +
	"\x11HeartbeatResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.network_node.v1.HeartbeatStatusEnumR\x06status\"L\n" +
	"\x14GetAliveNodesRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x04R\x05runId\x12\x1d\n" +
	"\n" +
	"outer_step\x18\x02 \x01(\x05R\touterStep\"8\n" +
	"\x15GetAliveNodesResponse\x12\x1f\n" +
	"\valive_nodes\x18\x01 \x03(\tR\n" +
	"aliveNodes\"\x81\x01\n" +
	"\x11SetBarrierRequest\x12\x1d\n" +
	"\n" +
	"barrier_id\x18\x01 \x01(\tR\tbarrierId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\x04R\x05runId\x12\x1d\n" +
	"\n" +
	"outer_step\x18\x04 \x01(\x05R\touterStep\"P\n" +
	"\x12SetBarrierResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".network_node.v1.BarrierStatusEnumR\x06status\"n\n" +
	"\x17GetBarrierStatusRequest\x12\x1d\n" +
	"\n" +
	"barrier_id\x18\x01 \x01(\tR\tbarrierId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\x04R\x05runId\x12\x1d\n" +
	"\n" +
	"outer_step\x18\x03 \x01(\x05R\touterStep\"u\n" +
	"\x18GetBarrierStatusResponse\x12\x1b\n" +
	"\tall_ready\x18\x01 \x01(\bR\ballReady\x12\x1b\n" +
	"\tnot_ready\x18\x02 \x03(\tR\bnotReady\x12\x1f\n" +
	"\valive_nodes\x18\x03 \x03(\tR\n" +
	"aliveNodes\"_\n" +
	"\x15SetStoreRecordRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x04R\x05runId\x12/\n" +
	"\x06record\x18\x02 \x01(\v2\x17.network_node.v1.RecordR\x06record\"0\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"X\n" +
	"\x16SetStoreRecordResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.network_node.v1.StoreRecordStatusEnumR\x06status\"@\n" +
	"\x15GetStoreRecordRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x04R\x05runId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"I\n" +
	"\x16GetStoreRecordResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.network_node.v1.RecordR\x06record\"-\n" +
	"\x14StoreListKeysRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x04R\x05runId\"+\n" +
	"\x15StoreListKeysResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys*F\n" +
	"\x15MLNodeTrainStatusEnum\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\n" +
	"\n" +
	"\x06JOINED\x10\x02\x12\x0e\n" +
	"\n" +
	"NOT_JOINED\x10\x03*<\n" +
	"\x13HeartbeatStatusEnum\x12\x10\n" +
	"\fHEARTBEAT_OK\x10\x00\x12\x13\n" +
	"\x0fHEARTBEAT_ERROR\x10\x01*-\n" +
	"\x11BarrierStatusEnum\x12\t\n" +
	"\x05READY\x10\x00\x12\r\n" +
	"\tNOT_READY\x10\x01*@\n" +
	"\x15StoreRecordStatusEnum\x12\x11\n" +
	"\rSET_RECORD_OK\x10\x00\x12\x14\n" +
	"\x10SET_RECORD_ERROR\x10\x012\xef\x06\n" +
	"\x12NetworkNodeService\x12X\n" +
	"\fJoinTraining\x12$.network_node.v1.JoinTrainingRequest\x1a\".network_node.v1.MLNodeTrainStatus\x12a\n" +
	"\x15GetJoinTrainingStatus\x12$.network_node.v1.JoinTrainingRequest\x1a\".network_node.v1.MLNodeTrainStatus\x12V\n" +
	"\rSendHeartbeat\x12!.network_node.v1.HeartbeatRequest\x1a\".network_node.v1.HeartbeatResponse\x12^\n" +
	"\rGetAliveNodes\x12%.network_node.v1.GetAliveNodesRequest\x1a&.network_node.v1.GetAliveNodesResponse\x12U\n" +
	"\n" +
	"SetBarrier\x12\".network_node.v1.SetBarrierRequest\x1a#.network_node.v1.SetBarrierResponse\x12g\n" +
	"\x10GetBarrierStatus\x12(.network_node.v1.GetBarrierStatusRequest\x1a).network_node.v1.GetBarrierStatusResponse\x12a\n" +
	"\x0eSetStoreRecord\x12&.network_node.v1.SetStoreRecordRequest\x1a'.network_node.v1.SetStoreRecordResponse\x12a\n" +
	"\x0eGetStoreRecord\x12&.network_node.v1.GetStoreRecordRequest\x1a'.network_node.v1.GetStoreRecordResponse\x12^\n" +
	"\rListStoreKeys\x12%.network_node.v1.StoreListKeysRequest\x1a&.network_node.v1.StoreListKeysResponseBKZIgithub.com/product-science/chain-protos/go/network_node/v1;network_nodev1b\x06proto3"

var (
	file_v1_network_node_proto_rawDescOnce sync.Once
	file_v1_network_node_proto_rawDescData []byte
)

func file_v1_network_node_proto_rawDescGZIP() []byte {
	file_v1_network_node_proto_rawDescOnce.Do(func() {
		file_v1_network_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_network_node_proto_rawDesc), len(file_v1_network_node_proto_rawDesc)))
	})
	return file_v1_network_node_proto_rawDescData
}

var file_v1_network_node_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_network_node_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_network_node_proto_goTypes = []any{
	(MLNodeTrainStatusEnum)(0),       // 0: network_node.v1.MLNodeTrainStatusEnum
	(HeartbeatStatusEnum)(0),         // 1: network_node.v1.HeartbeatStatusEnum
	(BarrierStatusEnum)(0),           // 2: network_node.v1.BarrierStatusEnum
	(StoreRecordStatusEnum)(0),       // 3: network_node.v1.StoreRecordStatusEnum
	(*JoinTrainingRequest)(nil),      // 4: network_node.v1.JoinTrainingRequest
	(*MLNodeTrainStatus)(nil),        // 5: network_node.v1.MLNodeTrainStatus
	(*HeartbeatRequest)(nil),         // 6: network_node.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 7: network_node.v1.HeartbeatResponse
	(*GetAliveNodesRequest)(nil),     // 8: network_node.v1.GetAliveNodesRequest
	(*GetAliveNodesResponse)(nil),    // 9: network_node.v1.GetAliveNodesResponse
	(*SetBarrierRequest)(nil),        // 10: network_node.v1.SetBarrierRequest
	(*SetBarrierResponse)(nil),       // 11: network_node.v1.SetBarrierResponse
	(*GetBarrierStatusRequest)(nil),  // 12: network_node.v1.GetBarrierStatusRequest
	(*GetBarrierStatusResponse)(nil), // 13: network_node.v1.GetBarrierStatusResponse
	(*SetStoreRecordRequest)(nil),    // 14: network_node.v1.SetStoreRecordRequest
	(*Record)(nil),                   // 15: network_node.v1.Record
	(*SetStoreRecordResponse)(nil),   // 16: network_node.v1.SetStoreRecordResponse
	(*GetStoreRecordRequest)(nil),    // 17: network_node.v1.GetStoreRecordRequest
	(*GetStoreRecordResponse)(nil),   // 18: network_node.v1.GetStoreRecordResponse
	(*StoreListKeysRequest)(nil),     // 19: network_node.v1.StoreListKeysRequest
	(*StoreListKeysResponse)(nil),    // 20: network_node.v1.StoreListKeysResponse
}
var file_v1_network_node_proto_depIdxs = []int32{
	0,  // 0: network_node.v1.MLNodeTrainStatus.status:type_name -> network_node.v1.MLNodeTrainStatusEnum
	1,  // 1: network_node.v1.HeartbeatResponse.status:type_name -> network_node.v1.HeartbeatStatusEnum
	2,  // 2: network_node.v1.SetBarrierResponse.status:type_name -> network_node.v1.BarrierStatusEnum
	15, // 3: network_node.v1.SetStoreRecordRequest.record:type_name -> network_node.v1.Record
	3,  // 4: network_node.v1.SetStoreRecordResponse.status:type_name -> network_node.v1.StoreRecordStatusEnum
	15, // 5: network_node.v1.GetStoreRecordResponse.record:type_name -> network_node.v1.Record
	4,  // 6: network_node.v1.NetworkNodeService.JoinTraining:input_type -> network_node.v1.JoinTrainingRequest
	4,  // 7: network_node.v1.NetworkNodeService.GetJoinTrainingStatus:input_type -> network_node.v1.JoinTrainingRequest
	6,  // 8: network_node.v1.NetworkNodeService.SendHeartbeat:input_type -> network_node.v1.HeartbeatRequest
	8,  // 9: network_node.v1.NetworkNodeService.GetAliveNodes:input_type -> network_node.v1.GetAliveNodesRequest
	10, // 10: network_node.v1.NetworkNodeService.SetBarrier:input_type -> network_node.v1.SetBarrierRequest
	12, // 11: network_node.v1.NetworkNodeService.GetBarrierStatus:input_type -> network_node.v1.GetBarrierStatusRequest
	14, // 12: network_node.v1.NetworkNodeService.SetStoreRecord:input_type -> network_node.v1.SetStoreRecordRequest
	17, // 13: network_node.v1.NetworkNodeService.GetStoreRecord:input_type -> network_node.v1.GetStoreRecordRequest
	19, // 14: network_node.v1.NetworkNodeService.ListStoreKeys:input_type -> network_node.v1.StoreListKeysRequest
	5,  // 15: network_node.v1.NetworkNodeService.JoinTraining:output_type -> network_node.v1.MLNodeTrainStatus
	5,  // 16: network_node.v1.NetworkNodeService.GetJoinTrainingStatus:output_type -> network_node.v1.MLNodeTrainStatus
	7,  // 17: network_node.v1.NetworkNodeService.SendHeartbeat:output_type -> network_node.v1.HeartbeatResponse
	9,  // 18: network_node.v1.NetworkNodeService.GetAliveNodes:output_type -> network_node.v1.GetAliveNodesResponse
	11, // 19: network_node.v1.NetworkNodeService.SetBarrier:output_type -> network_node.v1.SetBarrierResponse
	13, // 20: network_node.v1.NetworkNodeService.GetBarrierStatus:output_type -> network_node.v1.GetBarrierStatusResponse
	16, // 21: network_node.v1.NetworkNodeService.SetStoreRecord:output_type -> network_node.v1.SetStoreRecordResponse
	18, // 22: network_node.v1.NetworkNodeService.GetStoreRecord:output_type -> network_node.v1.GetStoreRecordResponse
	20, // 23: network_node.v1.NetworkNodeService.ListStoreKeys:output_type -> network_node.v1.StoreListKeysResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_network_node_proto_init() }
func file_v1_network_node_proto_init() {
	if File_v1_network_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_network_node_proto_rawDesc), len(file_v1_network_node_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_network_node_proto_goTypes,
		DependencyIndexes: file_v1_network_node_proto_depIdxs,
		EnumInfos:         file_v1_network_node_proto_enumTypes,
		MessageInfos:      file_v1_network_node_proto_msgTypes,
	}.Build()
	File_v1_network_node_proto = out.File
	file_v1_network_node_proto_goTypes = nil
	file_v1_network_node_proto_depIdxs = nil
}
