# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from network_node.v1 import network_node_pb2 as network__node_dot_v1_dot_network__node__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in network_node/v1/network_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRecord = channel.unary_unary(
                '/network_node.v1.RecordService/SetRecord',
                request_serializer=network__node_dot_v1_dot_network__node__pb2.SetRecordRequest.SerializeToString,
                response_deserializer=network__node_dot_v1_dot_network__node__pb2.SetRecordResponse.FromString,
                _registered_method=True)
        self.GetRecord = channel.unary_unary(
                '/network_node.v1.RecordService/GetRecord',
                request_serializer=network__node_dot_v1_dot_network__node__pb2.GetRecordRequest.SerializeToString,
                response_deserializer=network__node_dot_v1_dot_network__node__pb2.GetRecordResponse.FromString,
                _registered_method=True)


class RecordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRecord,
                    request_deserializer=network__node_dot_v1_dot_network__node__pb2.SetRecordRequest.FromString,
                    response_serializer=network__node_dot_v1_dot_network__node__pb2.SetRecordResponse.SerializeToString,
            ),
            'GetRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecord,
                    request_deserializer=network__node_dot_v1_dot_network__node__pb2.GetRecordRequest.FromString,
                    response_serializer=network__node_dot_v1_dot_network__node__pb2.GetRecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'network_node.v1.RecordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('network_node.v1.RecordService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network_node.v1.RecordService/SetRecord',
            network__node_dot_v1_dot_network__node__pb2.SetRecordRequest.SerializeToString,
            network__node_dot_v1_dot_network__node__pb2.SetRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network_node.v1.RecordService/GetRecord',
            network__node_dot_v1_dot_network__node__pb2.GetRecordRequest.SerializeToString,
            network__node_dot_v1_dot_network__node__pb2.GetRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
