# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network_node/v1/network_node.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'network_node/v1/network_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"network_node/v1/network_node.proto\x12\x0fnetwork_node.v1\"$\n\x06Record\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\";\n\x10SetRecordRequest\x12\'\n\x06record\x18\x01 \x01(\x0b\x32\x17.network_node.v1.Record\"$\n\x11SetRecordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x10GetRecordRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"<\n\x11GetRecordResponse\x12\'\n\x06record\x18\x01 \x01(\x0b\x32\x17.network_node.v1.Record2\xb7\x01\n\rRecordService\x12R\n\tSetRecord\x12!.network_node.v1.SetRecordRequest\x1a\".network_node.v1.SetRecordResponse\x12R\n\tGetRecord\x12!.network_node.v1.GetRecordRequest\x1a\".network_node.v1.GetRecordResponseB8Z6github.com/productscience/chain-protos/network_node/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_node.v1.network_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/productscience/chain-protos/network_node/v1'
  _globals['_RECORD']._serialized_start=55
  _globals['_RECORD']._serialized_end=91
  _globals['_SETRECORDREQUEST']._serialized_start=93
  _globals['_SETRECORDREQUEST']._serialized_end=152
  _globals['_SETRECORDRESPONSE']._serialized_start=154
  _globals['_SETRECORDRESPONSE']._serialized_end=190
  _globals['_GETRECORDREQUEST']._serialized_start=192
  _globals['_GETRECORDREQUEST']._serialized_end=223
  _globals['_GETRECORDRESPONSE']._serialized_start=225
  _globals['_GETRECORDRESPONSE']._serialized_end=285
  _globals['_RECORDSERVICE']._serialized_start=288
  _globals['_RECORDSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
